@startuml
hide methods
left to right direction

Title "Domain Model - Ranking Candidates"

skinparam class {
    LifeLineBorderColor DarkBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFFF
    ArrowColor grey
    BorderColor black
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor Green
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFDD
    ArrowColor DarkGrey
    BorderColor Black
}

package "Job Opening Aggregate"{
entity JobOpening <<entity>><<root>>

    card JobReference <<Value Object>> {
    }
    card TitleOrFunction <<Value Object>> {
    }
    card ContractType <<Value Object>> {
    }
    card Mode <<Value Object>> {
    }
    card Address <<Value Object>> {
    }
    card VacanciesNumber <<Value Object>> {
    }
    card Description <<Value Object>> {
    }

    JobOpening --> JobReference
    JobOpening --> TitleOrFunction
    JobOpening --> ContractType
    JobOpening --> Mode
    JobOpening --> Address
    JobOpening --> VacanciesNumber
    JobOpening --> Description

    note right of ContractType
        Can be one of the following:
        - full-time
        - part-time
    end note

    note right of Mode
         Can be one of the following:
         - remote
         - hybrid
         - onsite
    end note

}

package "Process Aggregate"{
entity Process <<entity>><<root>>

    card ProcessState <<Value Object>> {
    }
    card ProcessDate <<Value Object>> {
    }
    card ProcessStatus <<Value Object>>{
    }

    Process --> ProcessState
    Process --> ProcessDate
    Process --> ProcessStatus

    note right of ProcessDate
        Can be one of the following:
        - applicationStartDate
        - ScreeningStartDate
        - InterviewsStartDate
        - AnalysisStartDate
        - ResultStartDate
    end note

    note right of ProcessState
        Can be one of the following:
        - Application
        - Screening
        - Interviews
        - Analysis
        - Result
    end note

    note right of ProcessStatus
        Can be one of the following:
        - Open
        - Close
    end note
}

    JobOpening  --> Process

@enduml