@startuml
autonumber

actor CustomerManager

participant UploadResponsesUI <<presentation>>
participant UploadResponsesController <<controller>>

database JobInterviewRepository <<repository>>

activate CustomerManager

    CustomerManager -> UploadResponsesUI : asks to upload candidate responses
    activate UploadResponsesUI

        UploadResponsesUI -> CustomerManager : requests job interview id
    deactivate UploadResponsesUI

    CustomerManager -> UploadResponsesUI : inserts id
    activate UploadResponsesUI

        UploadResponsesUI -> UploadResponsesController : findInterviewByID(jobInterviewID)
        activate UploadResponsesController

            UploadResponsesController -> JobInterviewRepository : ofIdentity(jobInterviewID)
            activate JobInterviewRepository

                JobInterviewRepository --> UploadResponsesController : jobInterview
            deactivate JobInterviewRepository

            UploadResponsesController --> UploadResponsesUI : jobInterview
        deactivate UploadResponsesController

        UploadResponsesUI --> CustomerManager : requests file path
    deactivate UploadResponsesUI

    CustomerManager -> UploadResponsesUI : inserts file path
    activate UploadResponsesUI

        UploadResponsesUI -> UploadResponsesController : readFile(path)
        activate UploadResponsesController

            UploadResponsesController --> UploadResponsesUI : responses
        deactivate UploadResponsesController

        UploadResponsesUI --> CustomerManager : shows interview score for the selected \napplication and asks to rank it

        UploadResponsesUI -> UploadResponsesController : uploadResponses(responses, jobInterview)
        activate UploadResponsesController

            UploadResponsesController -> JobInterviewRepository : save(updatedJobInterview)
            activate JobInterviewRepository

                JobInterviewRepository --> UploadResponsesController : successful operation
            deactivate JobInterviewRepository

            UploadResponsesController --> UploadResponsesUI : successful operation
        deactivate UploadResponsesController

        UploadResponsesUI --> CustomerManager : shows success message
    deactivate UploadResponsesUI

deactivate CustomerManager

@enduml