@startuml
autonumber

actor CustomerManager

participant RankCandidatesUI <<presentation>>
participant RankCandidatesController <<controller>>

database JobOpeningRepository <<repository>>
database ApplicationRepository <<repository>>
database JobInterviewRepository <<repository>>

activate CustomerManager

    CustomerManager -> RankCandidatesUI : asks to rank candidates
    activate RankCandidatesUI

        RankCandidatesUI -> RankCandidatesController : getAllJobOpenings()
        activate RankCandidatesController

            RankCandidatesController -> JobOpeningRepository : findAll()
            activate JobOpeningRepository

                JobOpeningRepository --> RankCandidatesController : jobOpenings
            deactivate JobOpeningRepository

            RankCandidatesController --> RankCandidatesUI : jobOpenings
        deactivate RankCandidatesController

        RankCandidatesUI -> CustomerManager : lists job opening and asks to select one
    deactivate RankCandidatesUI

    CustomerManager -> RankCandidatesUI : selects job opening
    activate RankCandidatesUI

        RankCandidatesUI -> RankCandidatesController : getApplicationsForJobOpening(selectedJobOpening)
        activate RankCandidatesController

            RankCandidatesController -> ApplicationRepository : findByJobOpening(selectedJobOpening)
            activate ApplicationRepository

                ApplicationRepository --> RankCandidatesController : applications
            deactivate ApplicationRepository

            RankCandidatesController --> RankCandidatesUI : applications
        deactivate RankCandidatesController

loop while ranking all applications

        RankCandidatesUI -> RankCandidatesController : getLastJobInterview(currentApplication)
        activate RankCandidatesController
            note right of RankCandidatesController
            The application might not have interviews but the customer manager can still rank it.
            end note
            RankCandidatesController -> JobInterviewRepository : findByApplication(currentApplication)
            activate JobInterviewRepository

                JobInterviewRepository --> RankCandidatesController : interview
            deactivate JobInterviewRepository

            RankCandidatesController --> RankCandidatesUI : interview
        deactivate RankCandidatesController

        RankCandidatesUI --> CustomerManager : shows interview score for the current \napplication and asks to rank it
    deactivate RankCandidatesUI

    CustomerManager -> RankCandidatesUI : ranks the application
    activate RankCandidatesUI

        RankCandidatesUI -> RankCandidatesController : updateRank(rank, selectedApplication)
        activate RankCandidatesController

            RankCandidatesController -> ApplicationRepository : save(selectedApplication)
            activate ApplicationRepository

                ApplicationRepository --> RankCandidatesController : successful operation
            deactivate ApplicationRepository

            RankCandidatesController --> RankCandidatesUI : successful operation
        deactivate RankCandidatesController

        RankCandidatesUI --> CustomerManager : shows success message
    deactivate RankCandidatesUI

end loop

deactivate CustomerManager

@enduml