@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Ranking candidates

autonumber

actor "Customer Manager" as CMAN
participant ":System" as System

activate CMAN

    CMAN -> System : asks to rank candidates of a job opening
    activate System


       System --> CMAN : lists job opening and asks to select one
    deactivate System

    CMAN -> System : selects job opening
    activate System

loop while ranking all applications

        System --> CMAN : lists one of the applications for the selected job opening
    deactivate System

    CMAN -> System : ranks the application
    activate System

        System --> CMAN : displays operation success message
    deactivate System
end loop

deactivate CMAN

@enduml