@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - 1009

autonumber

actor "Customer Manager" as CM
participant ": System" as System

activate CM    

    CM -> System : Requests selection of requirement specification
    activate System

   System --> CM : Displays all job openings registered in the system and asks to select one
    deactivate System

    CM -> System : Selects the job opening
    activate System

        System --> CM : Displays all requirement specifications registered in the system
    deactivate System

    CM -> System : Selects the requirement specification or chooses to proceed with existing one (if defined previously)
    activate System

        System --> CM : Displays all chosen details and asks to confirm
    deactivate System

    CM -> System : Confirms all the data
    activate System

        System --> CM : Displays operation success
        deactivate System

@enduml