@ECHO OFF
ECHO Running the Customer App...
java -jar jobs4u.customer.app/target/jobs4u.customer.app-0.1.0.jar

ECHO Running the Candidate App...
java -jar jobs4u.candidate.app/target/jobs4u.candidate.app-0.1.0.jar

ECHO Running the Backoffice App...
java -jar jobs4u.backoffice.app/target/jobs4u.backoffice.app-0.1.0.jar