@startuml
skinparam linetype ortho
top to bottom direction

package ui{
class DisplayCandidateDataUI{
    + headline()
    + emptyMessage()
    + elements()
    + elementPrinter()
    + elementName()
    + listHeader()
    + doShow()
}
}


package "Candidates" {

package "application"{
class DisplayCandidateDataController{
    + allCandidates()
}
}

package "domain" {
class Candidate{
    - User user
    - Curriculum curriculum
    - TelephoneNumber telephoneNumber

    + Candidate( user, telephoneNumber, curriculum)
    + Candidate()
    + user()
    + curriculum()
    + identity()
    + sameAs (other)
    + equals(o)
    + toString()

}
}

package "repositories"{

class CandidateRepository{
    + allCandidates()
}
}

 package "services"{

class CandidateService{
    + findCandidate(telephoneNumber)
    + allCandidates()

}
}

}

package "authz" {
class AuthorizationService{
    + authorizationService()
    + ensureAuthenticatedUserHasAnyOf\n(Jobs4URoles.CUSTOMER_MANAGER, Jobs4URoles.POWER_USER)

}
}

package "Persistence" {

class PersistenceContext {
    + repositories()
    + PersistenceContext()
}

class RepositoryFactory{
    + newTransactionalContext()
    + users(TransactionalContext autoTx)
    + users()
    + customerUsers(TransactionalContext autoTx)
    + customerUsers()
    + signupRequests(TransactionalContext autoTx)
    + signupRequests()
    + jobOpenings(TransactionalContext autoTx)
    + jobOpenings()
    + applications(TransactionalContext autoTx)
    + applications()
}
}












DisplayCandidateDataUI -> DisplayCandidateDataController
DisplayCandidateDataController -> PersistenceContext
PersistenceContext -> RepositoryFactory
DisplayCandidateDataController --> AuthorizationService
DisplayCandidateDataController ---> CandidateService
CandidateService--> CandidateRepository
CandidateRepository -> Candidate

@enduml