@startuml
'skinparam linetype ortho
left to right direction

package "ui" {
class AddUserUI {
    + doShow()
    + showRoles(roleTypes)
    + buildRolesMenu(roleTypes)
    + buildCustomerManagerAvailableRoles(roleTypes)
    + buildOperatorAvailableRoles(roleTypes)
    +  headline()
}
}
package "authz"{
package "application" {
class AddUserController {
    + passwordGenerator(name)
    + addUser(username, password, firstName,
    lastName, email, roles, CurrentTimeCalendars.now())
    + addUser(username, password,
    firstName, lastName, email, roles)
    + registerNewUser(name,password,email,role)
    + getRoleTypes()
    + getAllRoles()
}
}


package "user" {
class UserManagementService {
    + UserManagementService(userRepo, policy, encoder)
    + registerNewUser( username,  rawPassword,
    firstName,  lastName,  email, roles, createdOn)
    + registerNewUser( username,  rawPassword,
    firstName,  lastName,  email, roles)
    + registerUser(username, password, name, email, roles)
    + activeUsers()
    + deactivatedUsers()
    + allUsers()
    + userOfIdentity(id)
    + deactivateUser(user)
    + activateUser(user)
}

class Jobs4UPasswordPolicy {
    + isSatisfiedBy(rawPassword)
    + passwordGenerator(name)
    + strength(rawPassword)
}
}

}


AddUserUI ---> AddUserController

AddUserController ---> Jobs4UPasswordPolicy

AddUserController ---> UserManagementService

@enduml