@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Customer Manager" as CM
participant ": System" as System

activate CM    

    CM -> System : asks to register a new Job Opening
    activate System

       System --> CM : requests job opening details (Description, VacanciesNumber, Company,\n Address, Mode, ContractType, TitleOrFunction, JobReference)
    deactivate System

    CM -> System : submits Job Opening details
    activate System

        System --> CM : shows all details for the new job opening request and asks to confirm
    deactivate System

    CM -> System : confirms all the data
    activate System

        System --> CM : displays operation success
        deactivate System

@enduml