@startuml
autonumber

actor CustomerManager

participant NotifyCandidatesUI <<presentation>>
participant NotifyCandidatesController <<controller>>

participant ApplicationService <<service>>
participant EmailService <<service>>

database ApplicationRepository <<repository>>

activate CustomerManager

    CustomerManager -> NotifyCandidatesUI : asks to rank candidates
    activate NotifyCandidatesUI

        NotifyCandidatesUI -> NotifyCandidatesController : findApplicationsToNotify()
        activate NotifyCandidatesController

            NotifyCandidatesController -> ApplicationService : allApplications()
            activate ApplicationService

                ApplicationService -> ApplicationRepository : findAll()
                activate ApplicationRepository

                    ApplicationRepository --> ApplicationService : applications
                deactivate ApplicationRepository

                ApplicationService --> NotifyCandidatesController : applications
            deactivate ApplicationService

            NotifyCandidatesController --> NotifyCandidatesUI : applications
        deactivate NotifyCandidatesController

        NotifyCandidatesUI --> CustomerManager : shows how many emails will be sent

loop for each email

        NotifyCandidatesUI -> NotifyCandidatesController : findCandidateEmail(application)
        activate NotifyCandidatesController

                NotifyCandidatesController --> NotifyCandidatesUI : candidateEmail
        deactivate NotifyCandidatesController

        NotifyCandidatesUI -> NotifyCandidatesController : checkApplicationStatus(application)
        activate NotifyCandidatesController

            NotifyCandidatesController --> NotifyCandidatesUI : applicationStatus
        deactivate NotifyCandidatesController

        NotifyCandidatesUI -> NotifyCandidatesController : createEmail(candidateEmail, subject, body)
        activate NotifyCandidatesController

            NotifyCandidatesController -> EmailService : createEmail(candidateEmail, subject, body)
            activate EmailService

                EmailService --> NotifyCandidatesController : email
            deactivate EmailService

            NotifyCandidatesController --> NotifyCandidatesUI : email
        deactivate NotifyCandidatesController

end loop

        NotifyCandidatesUI -> NotifyCandidatesController : sendEmails(emailsToSend)
        activate NotifyCandidatesController

            NotifyCandidatesController -> EmailService : sendAllEmails(emailsToSend)
            activate EmailService
                note right
                    send through follow up server
                end note
                EmailService --> NotifyCandidatesController : successfull operation
            deactivate EmailService

            NotifyCandidatesController --> NotifyCandidatesUI : successfull operation
        deactivate NotifyCandidatesController

        NotifyCandidatesUI --> CustomerManager : shows operation success
    deactivate NotifyCandidatesUI

deactivate CustomerManager

@enduml