@startuml
'skinparam linetype ortho
left to right direction

class ActivateUserUI {
    + doShow()
    + headline()
}

class ActivateUserController {
    + deactivatedUsers()
    + activateUser(systemUser)
}

interface RepositoryFactory {
    + newTransactionalContext()
    + users(TransactionalContext autoTx)
    + users()
    + customerUsers(TransactionalContext autoTx)
    + customerUsers()
    + signupRequests(TransactionalContext autoTx)
    + signupRequests()
    + jobOpenings(TransactionalContext autoTx)
    + jobOpenings()
    + applications(TransactionalContext autoTx)
    + applications()
}

class PersistenceContext {
    + repositories()
    + PersistenceContext()
}

class UserManagementService {
    + UserManagementService(userRepo, policy, encoder)
    + registerNewUser( username,  rawPassword,
    firstName,  lastName,  email, roles, createdOn)
    + registerNewUser( username,  rawPassword,
    firstName,  lastName,  email, roles)
    + registerUser(username, password, name, email, roles)
    + activeUsers()
    + deactivatedUsers()
    + allUsers()
    + userOfIdentity(id)
    + deactivateUser(user)
    + activateUser(user)
}



ActivateUserUI ---> ActivateUserController

ActivateUserController ---> UserManagementService

ActivateUserController ---> PersistenceContext


PersistenceContext ---> RepositoryFactory

@enduml