@startuml
skinparam linetype ortho
'left to right direction

class AddUserUI {
    + doShow()
    + showRoles(roleTypes)
    + buildRolesMenu(roleTypes)
    + buildCustomerManagerAvailableRoles(roleTypes)
    + buildOperatorAvailableRoles(roleTypes)
    +  headline()
}

class ActivateUserUI {
    + doShow()
    + headline()
}

class DeactivateUserUI {
    + doShow()
    + headline()
}

class ListBackofficeUsersUI {
    + elements()
    + headline()
    + emptyMessage()
    + elementPrinter()
    + elementName()
    + listHeader()
    + doShow()
}

class AddUserController {
    + passwordGenerator(name)
    + addUser(username, password, firstName,
    lastName, email, roles, CurrentTimeCalendars.now())
    + addUser(username, password,
    firstName, lastName, email, roles)
    + registerNewUser(name,password,email,role)
    + getRoleTypes()
    + getAllRoles()
}

class ActivateUserController {
    + deactivatedUsers()
    + activateUser(systemUser)
}

class DeactivateController {
    + activeUsers()
    + deactivateUser(systemUser)
}

class ListUsersController {
    + allUsers()
    + allBackofficeUsers()
}

class Jobs4UPasswordPolicy {
    + isSatisfiedBy(rawPassword)
    + passwordGenerator(name)
    + strength(rawPassword)
}

class AuthorizationService {
    + authorizationService()
    + ensureAuthenticatedUserHasAnyOf(Jobs4URoles.CUSTOMER_MANAGER, Jobs4URoles.POWER_USER)
}

class RepositoryFactory {
    + newTransactionalContext()
    + users(TransactionalContext autoTx)
    + users()
    + customerUsers(TransactionalContext autoTx)
    + customerUsers()
    + signupRequests(TransactionalContext autoTx)
    + signupRequests()
    + jobOpenings(TransactionalContext autoTx)
    + jobOpenings()
    + applications(TransactionalContext autoTx)
    + applications()
}

class PersistenceContext {
    + repositories()
    + PersistenceContext()
}

class UserManagementService {
    + UserManagementService(userRepo, policy, encoder)
    + registerNewUser( username,  rawPassword,
    firstName,  lastName,  email, roles, createdOn)
    + registerNewUser( username,  rawPassword,
    firstName,  lastName,  email, roles)
    + registerUser(username, password, name, email, roles)
    + activeUsers()
    + deactivatedUsers()
    + allUsers()
    + userOfIdentity(id)
    + deactivateUser(user)
    + activateUser(user)
}


AddUserUI ---> AddUserController

AddUserController ---> Jobs4UPasswordPolicy

AddUserController ---> AuthorizationService

AddUserController ---> UserManagementService

AddUserController ---> PersistenceContext


ActivateUserUI ---> ActivateUserController

ActivateUserController ---> AuthorizationService

ActivateUserController ---> UserManagementService

ActivateUserController ---> PersistenceContext


DeactivateUserUI ---> DeactivateController

DeactivateController ---> AuthorizationService

DeactivateController ---> UserManagementService

DeactivateController ---> PersistenceContext


ListBackofficeUsersUI ---> ListUsersController

ListUsersController ---> AuthorizationService

ListUsersController ---> UserManagementService

ListUsersController ---> PersistenceContext


UserManagementService ---> SystemUserBuilder

UserManagementService ---> UserRepository

UserManagementService ---> SystemUser


PersistenceContext ---> RepositoryFactory

@enduml