@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - 1008

autonumber

actor "Language Engineer" as LE
participant ": System" as System

activate LE

    LE -> System : asks to deploy and configure a plugin
    activate System

        System --> LE: asks if it's a plugin for a Job\n Requirement Specification or for an Interview Model
    deactivate System

    LE -> System : submits the answer
    activate System

    alt Plugin for a Job Requirement Specification

        System --> LE: asks for the name to give to the plugin
    deactivate System

    LE -> System : submits the plugin's name
    activate System

    loop while the Language Engineer submits requirements to be used

        System --> LE: asks for requirements to be added
    deactivate System

    LE -> System : submits requirements
    activate System

    end loop

        System --> LE: displays all the data inserted and asks for confirmation
    deactivate System

    LE -> System : confirms all the data
    activate System

        System --> LE: generates the template text file with the requirements to be \nevaluated and the possible answers for each requirement

    else Plugin for an Interview Model

     loop while the Language Engineer submits questions to be used

        System --> LE: asks for the questions to be added
    deactivate System

    LE -> System : submits questions

    activate System
     end loop

         System --> LE: displays all the data inserted and asks for confirmation
     deactivate System

     LE -> System : confirms all the data
     activate System

     System --> LE: generates the template text file with the questions to be \nasked in the interview and the possible answers for each question

     deactivate System

    end

@enduml