@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Candidate" as C
participant ": System" as S

activate C

    C -> S: asks to list all of his notifications
    activate S

        S --> C : list all applications of candidate \nand display operation success
        deactivate S

@enduml