ei -@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Customer Manager" as CM
participant ":System" as System

activate CM

    CM -> System : asks to selects a job opening
    activate System

        System --> CM : shows the list of job opening
    deactivate System

    CM -> System : selects a job opening
    activate System

    System --> CM : list all applications of that  job opening
    deactivate System




@enduml