@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Registering a candidate

autonumber

actor "Operator" as OPERATOR
participant ":System" as System

activate OPERATOR

    OPERATOR -> System : asks to register a new user
    activate System


       System --> OPERATOR : requests account opening details (Email, FirstName, LastName)
    deactivate System

    OPERATOR -> System : inserts requested details
    activate System

        System --> OPERATOR : displays role options (no role / candidate)
    deactivate System

    OPERATOR -> System : selects role candidate
    activate System

        System --> OPERATOR : displays operation success
    deactivate System

deactivate OPERATOR

@enduml