@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Registering a candidate

autonumber

actor "Operator" as OPERATOR
participant ":System" as System

activate OPERATOR

    OPERATOR -> System : asks to register a new candidate
    activate System


       System --> OPERATOR : requests account opening details (FirstName, LastName,\n Email, TelephoneNumber, Curriculum)
    deactivate System

    OPERATOR -> System : inserts requested details
    activate System

        System --> OPERATOR : displays operation success
    deactivate System

deactivate OPERATOR

@enduml