@startuml
hide methods
left to right direction
'skinparam linetype ortho

Title "Domain Model"


package "Job Requirements Specification Aggregate"{
entity JobRequirementsSpecification <<entity>><<root>>

    card Requirements <<Value Object>>{
    }

    JobRequirementsSpecification --> Requirements

}

package "Operator Aggregate"{
    entity Operator <<entity>><<root>>

}

Operator-> JobRequirementsSpecification


@enduml