@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Customer Manager" as CM
participant ": System" as System

activate CM

    CM -> System : asks to deactivate a user
    activate System

       System --> CM : asks to select a user to deactivate
    deactivate System

    CM -> System : selects user
    activate System

        System --> CM : displays operation success
        deactivate System

@enduml