@startuml
hide methods
left to right direction

Title "Domain Model"

skinparam class {
    LifeLineBorderColor DarkBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFFF
    ArrowColor grey
    BorderColor black
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor Green
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFDD
    ArrowColor DarkGrey
    BorderColor Black
}

package "Admin Aggregate" {
entity Admin <<entity>><<root>>

    card AdminName <<Value Object>> {
    }
    card AdminEmail <<Value Object>> {
    }

        Admin --> AdminEmail
        Admin --> AdminName
}

package "Customer Manager Aggregate"{
entity CustomerManager <<entity>><<root>>

    card ManagerName <<Value Object>> {
    }
    card ManagerEmail <<Value Object>> {
    }

        CustomerManager --> ManagerName
        CustomerManager --> ManagerEmail

}

package "Customer Aggregate"{
entity Customer <<entity>><<root>>

    card CustomerName <<Value Object>> {
    }
    card CustomerEmail <<Value Object>> {
    }
    card CustomerPhoneNumber <<Value Object>> {
    }
    card CustomerPassword <<Value Object>> {
    }

        Customer --> CustomerEmail
        Customer --> CustomerName
        Customer --> CustomerPhoneNumber
        Customer --> CustomerPassword
}

package "Operator Aggregate"{
entity Operator <<entity>><<root>>

    card OperatorName <<Value Object>> {
    }
    card OperatorEmail <<Value Object>> {
    }

        Operator --> OperatorEmail
        Operator --> OperatorName

}

package "Candidate Aggregate"{
entity Candidate <<entity>><<root>>

    card CandidateName <<Value Object>> {
    }
    card CandidateEmail <<Value Object>> {
    }
    card CandidatePhoneNumber <<Value Object>> {
    }
    card CandidatePassword <<Value Object>> {
    }
    card Curriculum <<Value Object>> {
    }

        Candidate --> CandidateEmail
        Candidate --> CandidateName
        Candidate --> CandidatePhoneNumber
        Candidate --> CandidatePassword
        Candidate --> Curriculum

}

package "Language Engineer Aggregate"{
entity LanguageEngineer <<entity>><<root>>

    card EngineerName <<Value Object>> {
    }
    card EngineerEmail <<Value Object>> {
    }

        LanguageEngineer --> EngineerEmail
        LanguageEngineer --> EngineerName

entity JobRequirementsSpecification <<entity>><<root>>

    card RequirementsAnswers <<Value Object>>{
    }

        JobRequirementsSpecification --> RequirementsAnswers

}

package "Job Opening Aggregate"{
entity JobOpening <<entity>><<root>>

    card JobReference <<Value Object>> {
    }
    card TitleOrFunction <<Value Object>> {
    }
    card ContractType <<Value Object>> {
    }
    card Mode <<Value Object>> {
    }
    card Address <<Value Object>> {
    }
    card Company <<Value Object>> {
    }
    card VacanciesNumber <<Value Object>> {
    }
    card Description <<Value Object>> {
    }

    JobOpening --> JobReference
    JobOpening --> TitleOrFunction
    JobOpening --> ContractType
    JobOpening --> Mode
    JobOpening --> Address
    JobOpening --> Company
    JobOpening --> VacanciesNumber
    JobOpening --> Description

    note right of ContractType
        Can be one of the following:
        - full-time
        - part-time
    end note

    note right of Mode
         Can be one of the following:
         - remote
         - hybrid
         - onsite
    end note
}

package "Application Aggregate"{
entity Application <<entity>><<root>>

    card EmailContentFile <<Value Object>> {
    }
    card EmailFilesAttached <<Value Object>>{
    }
    card FilesAttachedContent <<Value Object>>{
    }
    card ApplicationDataFile <<Value Object>>{
    }
    card Status <<Value Object>>{
    }
    card SubmissionDate <<Value Object>>{
    }

    Application --> EmailContentFile
    Application --> EmailFilesAttached
    Application --> FilesAttachedContent
    Application --> ApplicationDataFile
    Application --> Status
    Application --> SubmissionDate

    note right of Status
        Can be one of the following:
        - submitted
        - pending
        - accepted
        - declined
    end note

    entity JobInterview <<entity>><<root>>

        card InterviewModel <<Value Object>> {
        }
        card Result <<Value Object>> {
        }
        card InterviewTime <<Value Object>> {
        }

        JobInterview --> InterviewModel
        JobInterview --> Result
        JobInterview --> InterviewTime

    note right of InterviewModel
        At least the following type of questions should be supported:
        - true/false
        - short text answer
        - choice (single answer)
        - choice (multiple answer)
        - integer number
        - decimal number
        - date
        - time
        - numeric scale
    end note
}

    CustomerManager --> "N " JobOpening : manages

    JobOpening --> "N " Application : has
    JobOpening --> Customer : associated

    Application --> Candidate

    JobInterview --> "1" Candidate

    Admin --> "N " Operator : manages
    Admin --> "N     " CustomerManager : manages
    Admin --> "N     " LanguageEngineer : manages

    Candidate --> "  N" JobOpening : apply

    Operator --> "N   " Application : monitors

    LanguageEngineer --> "N" JobRequirementsSpecification : create/manages

    JobRequirementsSpecification --> JobOpening : associated

@enduml