@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Candidate Login

autonumber

actor "Candidate" as CANDIDATE
participant ":System" as System

activate CANDIDATE

    CANDIDATE -> System : asks to login as a candidate
    activate System

        System --> CANDIDATE : requests account login details (Email, Password)
    deactivate System

    CANDIDATE -> System : inserts requested details
    activate System

        System --> CANDIDATE : displays operation success
    deactivate System

deactivate CANDIDATE

@enduml