@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title "Sequence Diagram - 1001"

'hide footbox

actor CustomerManager

participant RegisterCustomerUI <<presentation>>
participant RegisterCustomerController<<application>>
participant UserManagementService <<service>>
participant SystemUserBuilder <<userBuilder>>
participant UserRepository <<repository>>
participant SystemUser <<systemUser>>
participant PersistenceContext<<persistence>>
participant RepositoryFactory<<factory>>





@enduml