@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - 1001

autonumber

actor "Customer Manager" as CM
participant ": System" as System

activate CM    

    CM -> System : Asks to register a Customer
    activate System

        System --> CM : Asks for the customer's information
    deactivate System

    CM -> System : firstName, lastName, email, chooseToCreateOrToSelectAnExistentCompany
    activate System

    opt choose to select a company

    System --> CM : asks to select one company

    deactivate System

    CM -> System : selects one company

    else choose to create a company

    activate System

    System --> CM : asks for the company's name

    deactivate System

    CM -> System : companyName

    activate System

    end

    System --> CM : shows operation's success

    deactivate System

@enduml