@startuml
hide methods
left to right direction
'skinparam linetype ortho

Title "Domain Model"

skinparam class {
    LifeLineBorderColor DarkBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFFF
    ArrowColor grey
    BorderColor black
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor Green
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFDD
    ArrowColor DarkGrey
    BorderColor Black
}


package "Customer Manager Aggregate"{
entity CustomerManager <<entity>><<root>>

    card CustomerManagerEmail <<Value Object>> {
    }
    card CustomerManagerName <<Value Object>> {
    }

    CustomerManager --> CustomerManagerEmail
    CustomerManager --> CustomerManagerName
}
package "Candidate Aggregate"{
entity Candidate <<entity>><<root>>

    card CandidateName <<Value Object>> {
    }
    card CandidateEmail <<Value Object>> {
    }
    card CandidatePhoneNumber <<Value Object>> {
    }
    card CandidatePassword <<Value Object>> {
    }
    card Curriculum <<Value Object>> {
    }

        Candidate --> CandidateEmail
        Candidate --> CandidateName
        Candidate --> CandidatePhoneNumber
        Candidate --> CandidatePassword
        Candidate --> Curriculum
}



CustomerManager --> Candidate

}


@enduml