@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Ranking candidates

autonumber

actor "Customer Manager" as CM
participant ":System" as System

activate CM

    CM -> System : asks to change status of a phase of a job opening
    activate System


       System --> CM : lists job opening and asks to select one
    deactivate System

    CM -> System : selects job opening
    activate System

        System --> CM : lists current phase for the selected job opening \n and asks to move back actor forward
    deactivate System

    CM -> System : selects option
    activate System

        System --> CM : displays updated phase for the job opening \n and operation sucess
    deactivate System

deactivate CM

@enduml