@startuml
'skinparam linetype ortho
'left to right direction

class Customer

class CustomerRepository

class CreateJobOpeningController
class CustomerManager {
    - CustomerManagerName
    - CustomerManagerEmail
}

class CustomerManagerFactory {}

class JobRequirementsSpecification {
   - String Requirements
}
class JobRequirementsSpecificationFactory {}

class JobOpening {
   - String Description
   - String VacanciesNumber
   - String Address
   - Mode
   - ContractType
   - TitleOrFunction
   - JobReference
}
class JobOpeningFactory {}
class RepositoryFactory {}



RepositoryFactory "\lCustomerManagerFactory           " ---> "1" CustomerManagerFactory
RepositoryFactory "\n\n\n\n\nJobOpeningFactory" ---> "1" JobOpeningFactory
RepositoryFactory "\n\n\nJobRequirements\nSpecification\nFactory" ---> "1" JobRequirementsSpecificationFactory

CustomerManagerFactory "\nCustomerManagers" --> "*" CustomerManager
JobOpeningFactory "\nJobOpenings" --> "*" JobOpening
JobRequirementsSpecificationFactory "\nJobRequirementsSpecification" --> "*" JobRequirementsSpecification





@enduml