@startuml
skinparam linetype ortho
'left to right direction

class Customer {}

class CustomerRepository {}

class CreateJobOpeningUI {
    +createJobOpening(description, vacanciesNumber,address,
    mode, contractType,titleOrFunction, jobReference, processDate)
}

class CreateJobOpeningController {
    + repositories()
    + companies()
    + findCompanyByCode(companyName)
    + create(description, vacanciesNumber, address,
    mode, contractType,titleOrFunction, jobReference)
    + save(jobOpening)
}

class JobOpening {
   - String Description
   - String VacanciesNumber
   - String Address
   - Mode
   - ContractType
   - TitleOrFunction
   - JobReference
}

class JobOpeningRepository {
}

class PersistenceContext {}

class RepositoryFactory {}



CreateJobOpeningUI -> CreateJobOpeningController

CreateJobOpeningController --> PersistenceContext

CreateJobOpeningController --> RepositoryFactory

CreateJobOpeningController --> CustomerRepository

CreateJobOpeningController --> Customer

CreateJobOpeningController --> JobOpening

CreateJobOpeningController --> JobOpeningRepository





@enduml