@startuml
skinparam linetype ortho
left to right direction

class CreateJobOpeningUI {
    + doShow()
    + showModes()
    + showContractTypes()
    + addJobOpening(jobReference, description,
    vacanciesNumber, address, modes, contractTypes, \ntitleOrFunction)
    +headline()
}

class CreateJobOpeningController {
    + repositories()
    + companies()
    + findCompanyByCode(companyName)
    + addJobOpening(jobReference, description,
    vacanciesNumber, address, modes, contractTypes, \ntitleOrFunction)
}

class JobOpening {
   - String Description
   - String VacanciesNumber
   - String Address
   - Mode
   - ContractType
   - TitleOrFunction
   - JobReference

   + JobOpening(jobReference, description,
   vacanciesNumber, address, modes, contractTypes, \ntitleOrFunction)
   + identity()
   + sameAs(object)
   + jobReference()
   + description()
   + vacanciesNumber()
   + address()
   + mode()
   + contractType()
   + titleOrFunction()
}

class JobOpeningRepository {
    + allJobOpenings()
}

class JobOpeningService {
    + registerJobOpening(jobReference, description, vacanciesNumber,
    address, mode, contractType, titleOrFunction);
    + allJobOpenings()
}

class JobOpeningBuilder {
    + withAll(jobReference, description, vacanciesNumber, address, mode, contractType, titleOrFunction)
    + build()
}

class AuthorizationService {
    + authorizationService()
    + ensureAuthenticatedUserHasAnyOf(Jobs4URoles.CUSTOMER_MANAGER, Jobs4URoles.POWER_USER)
}

class PersistenceContext {
    + repositories()
    + PersistenceContext()
}

class RepositoryFactory {
    + newTransactionalContext()
    + users(TransactionalContext autoTx)
    + users()
    + customerUsers(TransactionalContext autoTx)
    + customerUsers()
    + signupRequests(TransactionalContext autoTx)
    + signupRequests()
    + jobOpenings(TransactionalContext autoTx)
    + jobOpenings()
    + applications(TransactionalContext autoTx)
    + applications()
}


CreateJobOpeningUI -> CreateJobOpeningController

CreateJobOpeningController --> PersistenceContext

CreateJobOpeningController -> JobOpeningService

CreateJobOpeningController -> AuthorizationService

JobOpeningService -> JobOpeningRepository

JobOpeningService -> JobOpeningBuilder

JobOpeningBuilder -> JobOpening

PersistenceContext -> RepositoryFactory

@enduml