@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Notify rank of candidates

autonumber

actor "Customer Manager" as CM
participant ":System" as System

activate CM

    CM -> System : asks to order the candidates of a job opening by grades
    activate System


       System --> CM : lists job openings and asks to select one
    deactivate System

    CM -> System : selects job opening
    activate System

loop application with status accepted
        System --> CM :show the result of notifications of the email to candidates
end

    System --> CM : show the result of notification of the email to costumer

    deactivate System

deactivate CM

@enduml

