@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Candidate Sign-Up/Login

autonumber

actor "Candidate" as CANDIDATE
participant ":System" as System

activate CANDIDATE

    CANDIDATE -> System : asks to sign-up/login as a candidate
    activate System

    alt Sign-Up option is selected
       System --> CANDIDATE : requests account opening details (Username, FirstName, LastName,\n Password, Email, CardNumber)

    else Login option is selected
        System --> CANDIDATE : requests account login details (Username, Password)

    deactivate System
    end

    CANDIDATE -> System : inserts requested details
    activate System

        System --> CANDIDATE : displays operation success
    deactivate System

@enduml