@startuml
autonumber

actor User

participant SignUpUI <<presentation>>
participant SignUpController <<controller>>
participant Jobs4UPasswordPolicy <<policy>>
participant SignUpBuilder <<builder>>
database UserRepository <<repository>>

activate User
    note right of User
        The user role depends on the app he is using.
    end note
    User -> SignUpUI: asks to sign-up

    activate SignUpUI

        SignUpUI --> User: asks for first name, last name, \nemail and telephone number
    deactivate SignUpUI

    User -> SignUpUI: provides details
    activate SignUpUI

        SignUpUI -> SignUpController : ...SignUpUI
        activate SignUpController

            SignUpController -> Jobs4UPasswordPolicy : passwordGenerator(firstName)
            activate Jobs4UPasswordPolicy

                Jobs4UPasswordPolicy --> SignUpController : returns password
            deactivate Jobs4UPasswordPolicy

            SignUpController -> SignUpBuilder : signUpBuilder(firstName, lastName, email, \ntelephoneNumber, password)
            activate SignUpBuilder

                SignUpBuilder --> SignUpController : returns signedUpUser
            deactivate SignUpBuilder

            SignUpController -> UserRepository : get
            activate UserRepository

                UserRepository --> SignUpController: returns userRepository
            deactivate UserRepository

            SignUpController -> UserRepository : find(email)
            activate UserRepository

                note left of UserRepository
                    returns false if
                    email doesn't exist
                    in the system
                end note
                UserRepository --> SignUpController : returns false
            deactivate UserRepository

            SignUpController -> UserRepository : save(signedUpUser)
            activate UserRepository

                UserRepository --> SignUpController : user created successfully
            deactivate UserRepository

            SignUpController --> SignUpUI : user created successfully
            deactivate SignUpController

        SignUpUI -> User: shows home page
    deactivate SignUpUI

deactivate User

@enduml