@startuml

title G007 - Support and apply authentication and authorization for all the users and functionalities

left to right direction
skinparam packageStyle rectangle

actor "Candidate" as CANDIDATE
actor "Customer" as CUSTOMER


actor "Admin" as ADMIN
actor "Operator" as OPERATOR
actor "Customer Manager" as CUSTOMER_MANAGER
actor "Language Engineer" as LANGUAGE_ENGINEER

rectangle "Candidate App" as candidateApp {
    usecase "Log in to Candidate App"

    CANDIDATE --> "Log in to Candidate App"
}

rectangle "Customer App" as customerApp {
    usecase "Log in to Customer App"

    CUSTOMER --> "Log in to Customer App"
}

rectangle "Backoffice" as backoffice {
    usecase "Log in to Backoffice"

    ADMIN --> "Log in to Backoffice"
    CUSTOMER_MANAGER --> "Log in to Backoffice"
    LANGUAGE_ENGINEER --> "Log in to Backoffice"
    OPERATOR --> "Log in to Backoffice"
}

@enduml