@startuml

autonumber

Title "Diagrama de Componentes e Interações"

participant ParentProcess
participant Watcher
participant ChildProcess

activate ParentProcess

ParentProcess -> Watcher : createWatcher()

activate Watcher

Watcher --> ParentProcess : directory´s information

deactivate Watcher

ParentProcess -> ParentProcess : createWorkers()

loop until parent process receive Ctrl+C
    Watcher -> ParentProcess : notifyNewFile()

    ParentProcess -> ChildProcess : sendFile()
    activate ChildProcess

    ChildProcess --> ParentProcess : fileProcessed()

    deactivate ChildProcess

end

ParentProcess --> Watcher : endWatcher()

deactivate ParentProcess

@enduml