@startuml
hide methods
left to right direction
'skinparam linetype ortho

Title "Domain Model"

skinparam class {
    LifeLineBorderColor DarkBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #F0FFFF
    ArrowColor grey
    BorderColor black
}

skinparam packageStyle rectangle

package "Interview Model Aggregate"{
entity InterviewModel <<entity>><<root>>

    card Plugin <<Value Object>> {
    }

    InterviewModel --> Plugin

}


package "Customer Manager Aggregate"{
entity CustomerManager <<entity>><<root>>

}

 CustomerManager -> InterviewModel


@enduml