@startuml
skinparam classAttributeIconSize 0

Title "Class Diagram - Select Requirement Specification"

package "ui"{
    class SelectRequirementsSpecificationUI{
    + doShow()
    + showJobOpenings()
    + selectFile()
    + selectJobOpening()
    }
}

package "Job Requirements Specifications"{
    package "application"{
    }
}

package "Job Opening"{
}
@enduml