name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "master"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run properties.sh
        run: ./properties.sh

      - name: Build with Maven
        run: mvn dependency:copy-dependencies verify -D maven.javadoc.skip=true --file pom.xml

      - name: Copy Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "jobs4u.bootstrap/target/*,deploy.sh"
          target: "~/deploy"
          rm: true

      - name: Deploy Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy
            killall java || true
            ./deploy.sh