# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# This workflow uses actions that are not certified by GitHub.

name: Java CI with Maven
run-name: ${{ github.actor }} committed at ${{ github.event_name }}

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # The workflow will run every day at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn surefire-report:report checkstyle:checkstyle -B package --file pom.xml

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}