# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# This workflow uses actions that are not certified by GitHub.

name: Java CI with Maven
run-name: ${{ github.actor }} committed at ${{ github.event_name }}

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # The workflow will run every day at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn surefire-report:report checkstyle:checkstyle -B package --file pom.xml

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: jobs4u.util.ci/target/site/jacoco-aggregate/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 0
          fail_below_threshold: false
          publish_only_summary: false

      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-markdown
          path: jobs4u.util.ci/target/site/jacoco-aggregate/coverage-results.md
          retention-days: 1